working on range implementation in check_fan

diff --git a/check_fan b/check_fan
--- a/check_fan
+++ b/check_fan
@@ -8,20 +8,19 @@ cat <<EOF
 Checks Fan RPM Status of Antminer
 Usage: $0 [-t] [-p api_port] [-f fan_number] [-h hostname] [-w warning_rpm] [-c critical_rpm]
 Command Summary:
-  -c critical_rpm	Critical treshold in RPM
+  -c low[:high]		Critical treshold (range) in RPM
   -f fan_number		Specify Fan number (Default: all)
   -H hostname		Antminer target
   -h				This help text
   -p api_port		Monitoring API Port (Default: TCP 4028)
-  -t				Reversed check logic. LOWER values than warning/critical will trigger.
-  -w warning_rpm	Warning treshold in RPM
+  -w low[:high]		Warning threshold (range) in RPM
 
 EOF
 }
 
 ## default values
 API_PORT=4028
-DESCENDING_CHECK_LOGIC=true
+MAX_INT=9223372036854775807
 
 ## exit statuses recognized by Nagios
 OK=0
@@ -58,25 +57,63 @@ is_absolute_path () {
     expr match "$1" '/' >/dev/null 2>/dev/null
 }
 
+is_number() {
+if ! [[ "$1" =~ ^[0-9]+$ ]]; then
+	die 1 "This is not a number: ${1}"
+fi
+}
+
+init_range () {
+LOWERMOST=0
+UPPERMOST=$MAX_INT
+
+
+if [ -n "${1}" ]; then
+	LOWERMOST=${1%:*}
+	UPPERMOST=${1#*:}
+
+	if [[ $LOWERMOST -eq $UPPERMOST ]]; then
+		UPPERMOST=$MAX_INT
+	fi
+fi
+
+is_number $LOWERMOST
+is_number $UPPERMOST
+
+echo "${LOWERMOST}:${UPPERMOST}"
+}
+
+is_value_within_range() {
+LOWERMOST=${2%:*}
+UPPERMOST=${2#*:}
+
+if [ "$1" -ge "$LOWERMOST" -a "$1" -le "$UPPERMOST" ]; then
+	RET=true;
+else
+	RET=false;
+fi
+
+echo $RET
+}
+
 ## parse command-line
-while getopts ":c:f:H:hptw:" opt; do
-  case ${opt} in
-    c ) CRITICAL_RPM=$OPTARG ;;
-    f ) FAN_NUMBER=$OPTARG ;;
-    H ) HOSTN=$OPTARG ;;
-    h ) usage; exit 0 ;;
-    p ) API_PORT=$OPTARG ;;
-    t ) DESCENDING_CHECK_LOGIC=false ;;
-    w ) WARNING_RPM=$OPTARG ;;
-    \? ) usage
-      echo "Invalid option: $OPTARG" 1>&2
-      exit 0
-      ;;
-    : )	usage
-      echo "Invalid option: $OPTARG requires an argument" 1>&2
-      exit 0
-      ;;
-  esac
+while getopts ":cf:H:hpw" opt; do
+	case ${opt} in
+		c ) CRITICAL_RPM_RANGE=$OPTARG ;;
+		f ) FAN_NUMBER=$OPTARG ;;
+		H ) HOSTN=$OPTARG ;;
+		h ) usage; exit 0 ;;
+		p ) API_PORT=$OPTARG ;;
+		w ) WARNING_RPM_RANGE=$OPTARG ;;
+		\? ) usage
+			echo "Invalid option: $OPTARG" 1>&2
+			exit 0
+			;;
+		: )	usage
+			echo "Invalid option: $OPTARG requires an argument" 1>&2
+			exit 0
+			;;
+	esac
 done
 
 ## required parameter checking
@@ -87,29 +124,8 @@ if [ -z "${FAN_NUMBER}" ]; then
 	die 1 "fan numbers not set. Type '$me -h' to get usage information."
 fi
 
-# check parameter types
-if ! [[ "$WARNING_RPM" =~ ^[0-9]+$ ]]; then
-	die 1 "WARNING_RPM is not a number: ${WARNING_RPM}"
-fi
-
-if ! [[ "$CRITICAL_RPM" =~ ^[0-9]+$ ]]; then
-	die 1 "CRITICAL_RPM is not a number: ${CRITICAL_RPM}"
-fi
-
-if ! [[ "$FAN_NUMBER" =~ ^[0-9]+$ ]]; then
-	die 1 "FAN_RPM is not a number: ${FAN_NUMBER}"
-fi
-
-# check if given thresholds makes sense
-if [ "$DESCENDING_CHECK_LOGIC" = true ]; then
-	if [ "$WARNING_RPM" -le $CRITICAL_RPM ]; then
-		die 1 "WARNING_RPM must be higher than CRITICAL_RPM"
-	fi
-else
-	if [ "$WARNING_RPM" -ge $CRITICAL_RPM ]; then
-		die 1 "WARNING_RPM must be lower than CRITICAL_RPM"
-	fi
-fi
+WARNING_RPM_RANGE=$(init_range "$WARNING_RPM_RANGE")
+CRITICAL_RPM_RANGE=$(init_range "$CRITICAL_RPM_RANGE")
 
 ## main
 
@@ -128,26 +144,17 @@ if ! [[ "$FAN_RPM" =~ ^[0-9]+$ ]]; then
 fi
 
 # check values
-if [ "$DESCENDING_CHECK_LOGIC" = true ] ; then
-	if [ "$FAN_RPM" -lt $CRITICAL_RPM ]; then
-		STATUS="CRITICAL - FAN${FAN} ${FAN_RPM} RPM (> ${CRITICAL_RPM})"
 
-	elif [ "$FAN_RPM" -lt $WARNING_RPM ]; then
-		STATUS="WARNING - FAN${FAN} ${FAN_RPM} RPM (> ${WARNING_RPM})"
 
-	else
-		STATUS="OK - FAN${FAN} ${FAN_RPM} RPM"
-	fi
+IS_CRITICAL=$(is_value_within_range "$FAN_RPM" "$CRITICAL_RPM_RANGE")
+IS_WARNING=$(is_value_within_range "$FAN_RPM" "$WARNING_RPM_RANGE")
+
+if [ "$IS_CRITICAL" = true ]; then
+	STATUS="CRITICAL - FAN${FAN} ${FAN_RPM} RPM"
+elif [ "$IS_WARNING" = true ]; then
+	STATUS="WARNING - FAN${FAN} ${FAN_RPM} RPM"
 else
-	if [ "$FAN_RPM" -gt $CRITICAL_RPM ]; then
-		STATUS="CRITICAL - FAN${FAN} ${FAN_RPM} RPM (< ${CRITICAL_RPM})"
-
-	elif [ "$FAN_RPM" -gt $WARNING_RPM ]; then
-		STATUS="WARNING - FAN${FAN} ${FAN_RPM} RPM (< ${WARNING_RPM})"
-
-	else
-		STATUS="OK - FAN${FAN} ${FAN_RPM} RPM"
-	fi
+	STATUS="OK - FAN${FAN} ${FAN_RPM} RPM"
 fi
 
 PERFDATA="FAN_RPM=${FAN_RPM};$WARNING;$CRITICAL;0;"
